# Generated by Django 5.0.2 on 2026-01-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDomainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('dns_records', models.JSONField()),
                ('whois_info', models.JSONField()),
                ('ssl_info', models.JSONField()),
                ('http_info', models.JSONField()),
                ('ip_info', models.JSONField()),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('server_location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
