# Generated by Django 5.0.2 on 2026-01-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_domain_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitedomaininfo',
            name='server_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
